{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "costgraph-selfhosted.fullname" . }}
  labels:
    {{- include "costgraph-selfhosted.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.ingestionApi.enabled }}
          - path: /api/v1/write
            pathType: Prefix
            backend:
              service:
                name: {{ include "costgraph-selfhosted.fullname" $ }}-ingestion-api
                port:
                  number: 8080
          {{- end }}
          {{- if $.Values.dashboard.enabled }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "costgraph-selfhosted.fullname" $ }}
                port:
                  number: 8080
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: {{ include "costgraph-selfhosted.fullname" $ }}
                port:
                  number: 8080
          {{- end }}
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if $.Values.dashboard.enabled }}
                name: {{ include "costgraph-selfhosted.fullname" $ }}-dashboard
                port:
                  number: 80
                {{- else }}
                name: {{ include "costgraph-selfhosted.fullname" $ }}
                port:
                  number: 8080
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
