{{- if and .Values.global.controlPlane.apiKey (not .Values.global.imagePullSecrets) }}
{{- $registry := (splitList "/" .Values.backend.deployment.image.repository) | first }}
{{- $auth := printf "x:%s" .Values.global.controlPlane.apiKey | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "costgraph-selfhosted.fullname" . }}-registry
  labels:
    {{- include "costgraph-selfhosted.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{%q:{"auth":%q}}}` $registry $auth | b64enc }}
{{- end }}
