{{- if and .Values.global.controlPlane.apiKey (not .Values.global.imagePullSecrets) }}
{{ include "costgraph.dockerConfigJsonSecret" (dict
    "ctx" $
    "name" (printf "%s-registry" (include "costgraph-selfhosted.fullname" .))
    "labels" (include "costgraph-selfhosted.labels" . | fromYaml)
    "registry" (splitList "/" .Values.backend.deployment.image.repository | first)
    "password" .Values.global.controlPlane.apiKey
) }}
{{- end }}
