apiVersion: v1
kind: Service
metadata:
  name: costgraph
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.costgraph.config.prometheus_metrics_port }}"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: costgraph
  ports:
    - protocol: TCP
      port: {{ .Values.costgraph.operator.port }}
      name: costgraph-api
      targetPort: {{ .Values.costgraph.operator.port }}
{{- if .Values.costgraph.config.costgraph_feature_flags.prometheus }}
    - protocol: TCP
      port: {{ .Values.costgraph.config.prometheus_metrics_port }}
      name: costgraph-metrics
      targetPort: {{ .Values.costgraph.config.prometheus_metrics_port }}
{{- end }}
  type: ClusterIP