{{ if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.config.postgres_host }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.config.postgres_port }}
      targetPort: {{ .Values.postgres.config.postgres_port }}
  selector:
    app: postgres
{{ end }}