{{ if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: {{ if .Values.postgres.pvc.enabled }} "StatefulSet" {{ else }} "Deployment" {{ end }}
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  annotations:
    checksum/supersetenv: {{ include "chart.supersetenv" . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{.Values.postgres.image}}:{{.Values.postgres.tag}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.postgres.config.postgres_port }}
          envFrom:
            - configMapRef:
                name: postgres
          resources:
{{- .Values.postgres.resources | toYaml | nindent 12 }}
{{- if .Values.postgres.pvc.enabled }}
          volumeMounts:
            - mountPath: {{.Values.postgres.config.pg_data_directory}}
              name: "postgres"
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.pvc.size }}
  serviceName: postgres
{{ end }}
{{ end }}