{{ if .Values.superset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 80
      name: costgraph-superset
      targetPort: {{ .Values.superset.port }}
  type: ClusterIP
{{ end }}