{{- $config := merge (dict) .Values.config -}}
{{- $_ := set $config "provider" .Values.provider -}}
{{- $_ := set $config "sink" "costgraph" -}}
{{- $_ := set $config "COSTGRAPH_URL" .Values.costgraph.url -}}
{{- with .Values.month }}{{- $_ := set $config "month" . -}}{{- end }}
{{- include "costgraph.configMap" (dict
    "ctx" .
    "name" (include "focus-exporter.configMapName" .)
    "labels" (include "focus-exporter.labels" . | fromYaml)
    "data" (dict "config.yaml" (toYaml $config))
  ) }}
