{{- if .Values.serviceAccount.create }}
{{- include "costgraph.serviceAccount" (dict
    "ctx" .
    "name" (include "focus-exporter.serviceAccountName" .)
    "labels" (include "focus-exporter.labels" . | fromYaml)
    "annotations" .Values.serviceAccount.annotations
    "automount" false
  ) }}
{{- end }}
