{{- $c := .Values.openCostApi }}
{{- if $c.enabled }}
{{- $w := $c.deployment }}
{{- $name := required "openCostApi.applicationName is required" $c.applicationName }}
{{- $component := "operator-opencost-api" }}
{{- $labels := fromYaml (include "costgraph-operator.componentLabels" (dict "ctx" $ "name" $name "component" $component)) }}
{{- $selectorLabels := fromYaml (include "costgraph-operator.componentSelectorLabels" (dict "ctx" $ "name" $name "component" $component)) }}
{{- $host := trimPrefix "https://" (trimPrefix "http://" (required "openCostApi.config.apiHost is required" $c.config.apiHost)) }}
{{- $conf := printf `server {
  listen %d;
  resolver %s ipv6=off;
  location / {
    proxy_set_header X-API-Key "${API_KEY}";
    proxy_set_header Host %s;
    proxy_ssl_server_name on;
    set $backend "https://%s";
    proxy_pass $backend%s$uri?$args&filter=cluster:%%22${CLUSTER_NAME}%%22;
  }
}
` (int $c.service.port) $c.config.resolver $host $host $c.config.basePath }}
{{- include "costgraph.configMap" (dict
    "ctx"    $
    "name"   (printf "%s-conf" $name)
    "labels" $labels
    "data"   (dict "default.conf.template" $conf)
) }}
{{- end }}
