{{- if not .Values.global.existingSecret }}
{{ include "costgraph.secret" (dict
    "ctx" $
    "name" (include "costgraph-operator.apiKeySecretName" .)
    "labels" (include "costgraph-operator.labels" . | fromYaml)
    "data" (dict "apiKey" (.Values.global.apiKey | required "global.apiKey must be set when global.existingSecret is not provided" | b64enc))
) }}
{{- end }}
