{{- if .Values.serviceAccount.create -}}
{{ include "costgraph.serviceAccount" (dict
    "ctx" $
    "name" (include "costgraph-operator.serviceAccountName" .)
    "labels" (include "costgraph-operator.labels" . | fromYaml)
    "annotations" .Values.serviceAccount.annotations
    "automount" .Values.serviceAccount.automount
) }}
{{- end }}
