apiVersion: v1
kind: ServiceAccount
metadata:
  name: costgraph
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-resources-view
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: costgraph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-resources-view
subjects:
- kind: ServiceAccount
  name: costgraph
  namespace: {{ .Values.namespace }}