apiVersion: v2
name: costgraph-operator
description: A Helm chart for the Costgraph operator
type: application
version: 0.1.4
appVersion: "1.16.1"

dependencies:
  - name: kube-state-metrics
    version: "5.27.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: cadvisor
    version: "0.1.*"
    repository: https://charts.bitnami.com/bitnami
    condition: cadvisor.enabled
  - name: dcgm-exporter
    version: "3.*"
    repository: https://nvidia.github.io/dcgm-exporter/helm-charts
    condition: dcgm-exporter.enabled
